default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: db

  username: root 
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'].sub('_development', '') %>_test 
  
production:
  <<: *default
  database: hair_app_production
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
