version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${RAILS_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  db:
    image: mysql:8.0
    container_name: hair_app_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: secure_password
      TZ: ${TZ}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${NEXT_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

volumes:
  db_data:
