version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: hair_app_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: secure_password
      TZ: ${TZ}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app:cached
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app:cached
    depends_on:
      - api
    command: npm run dev

volumes:
  db_data:
