source "https://rubygems.org"

gem "rails", "~> 8.0.3"

gem "mysql2", "~> 0.5"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "kamal", require: false

gem "thruster", require: false

gem "rack-cors"
gem 'devise'
gem 'devise_token_auth'
gem 'devise-i18n'

group :development, :test do
  gem 'rspec-rails'

  gem 'database_cleaner-active_record'

  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end
